DROP TABLE IF EXISTS Service;
CREATE TABLE IF NOT EXISTS Service(
type VARCHAR(50) PRIMARY KEY,
cost FLOAT(8,2) NOT NULL);


DROP TABLE IF EXISTS Employee;
CREATE TABLE IF NOT EXISTS Employee(
employeeID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
fName VARCHAR(30) NOT NULL,
lName VARCHAR(30) NOT NULL,
position VARCHAR(30) NOT NULL,
salary FLOAT(9,2) NOT NULL,
sex CHAR(1) NOT NULL,
DOB DATE NOT NULL,
address VARCHAR(50) NOT NULL,
phoneNo CHAR(10) NOT NULL,
SSN CHAR(9) NOT NULL,
bankAcctNo VARCHAR(17) NOT NULL,
bankRoutingNo CHAR(9) NOT NULL,
username VARCHAR(20) NOT NULL,
password CHAR(32) NOT NULL);


DROP TABLE IF EXISTS Patient;
CREATE TABLE IF NOT EXISTS Patient(
patientID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
fName VARCHAR(30) NOT NULL,
lName VARCHAR(30) NOT NULL,
sex CHAR(1),
DOB DATE NOT NULL,
address VARCHAR(50) NOT NULL,
phoneNo CHAR(10) NOT NULL,
insuranceProvider VARCHAR(30),
insuranceNo VARCHAR(10),
insurancePrimary VARCHAR(60));


DROP TABLE IF EXISTS SalaryPaid;
CREATE TABLE IF NOT EXISTS SalaryPaid(
date DATE NOT NULL,
employeeID INT UNSIGNED NOT NULL,
amount FLOAT(9,2) NOT NULL,
PRIMARY KEY (date, employeeID),
FOREIGN KEY (employeeID) REFERENCES Employee (employeeID));


DROP TABLE IF EXISTS Schedule;
CREATE TABLE IF NOT EXISTS Schedule(
employeeID INT UNSIGNED PRIMARY KEY NOT NULL,
workDays VARCHAR(7) NOT NULL,
startTime TIME NOT NULL,
endTime TIME NOT NULL,
FOREIGN KEY (employeeID) REFERENCES Employee (employeeID));


DROP TABLE IF EXISTS Immunization;
CREATE TABLE IF NOT EXISTS Immunization(
patientID INT UNSIGNED NOT NULL,
date DATE NOT NULL,
type VARCHAR(30) NOT NULL,
PRIMARY KEY (patientID, date, type),
FOREIGN KEY (patientID) REFERENCES Patient (patientID));


DROP TABLE IF EXISTS Appointment;
CREATE TABLE IF NOT EXISTS Appointment(
dateTime DATETIME NOT NULL,
patientID INT UNSIGNED NOT NULL,
employeeID INT UNSIGNED NOT NULL,
checkedIn CHAR(1) NOT NULL,
PRIMARY KEY (dateTime, patientID),
FOREIGN KEY (patientID) REFERENCES Patient (patientID),
FOREIGN KEY (employeeID) REFERENCES Employee (employeeID));


DROP TABLE IF EXISTS Visitation;
CREATE TABLE IF NOT EXISTS Visitation(
dateTime DATETIME NOT NULL,
patientID INT UNSIGNED NOT NULL,
reasonForVisit TEXT NOT NULL,
diagnosis TEXT NOT NULL,
serviceType VARCHAR(50) NOT NULL,
PRIMARY KEY (dateTime, patientID),
FOREIGN KEY (dateTime, patientID) REFERENCES Appointment (dateTime, patientID),
FOREIGN KEY (serviceType) REFERENCES Service (type));


DROP TABLE IF EXISTS HealthScreening;
CREATE TABLE IF NOT EXISTS HealthScreening(
dateTime DATETIME NOT NULL, 
patientID INT UNSIGNED NOT NULL,
smoker CHAR(1), 
pregnant CHAR(1),
height VARCHAR(6), 
weight INT(3) UNSIGNED, 
bloodPressure VARCHAR(7), 
HR VARCHAR(10),
currentMedications VARCHAR(50), 
PRIMARY KEY (dateTime, patientID),
FOREIGN KEY (dateTime, patientID) REFERENCES Appointment (dateTime, patientID));


DROP TABLE IF EXISTS Prescription;
CREATE TABLE IF NOT EXISTS Prescription(
date DATE NOT NULL, 
patientID INT UNSIGNED NOT NULL, 
type VARCHAR(50) NOT NULL,
employeeID INT UNSIGNED NOT NULL,
instruction VARCHAR(100), 
PRIMARY KEY (date, patientID, type),
FOREIGN KEY(patientID) REFERENCES Patient(patientID));


DROP TABLE IF EXISTS MedicalTest;
CREATE TABLE IF NOT EXISTS MedicalTest(
date DATE NOT NULL, 
type VARCHAR(50) NOT NULL, 
patientID INT UNSIGNED NOT NULL, 
testLocation VARCHAR(50), 
aDate DATE, 
result VARCHAR(100), 
PRIMARY KEY(date, type, patientID),
FOREIGN KEY(patientID) REFERENCES Patient(patientID));


DROP TABLE IF EXISTS Bill;
CREATE TABLE IF NOT EXISTS Bill(
billNo INT UNSiGNED AUTO_INCREMENT NOT NULL, 
status_bill VARCHAR(20),
dateTime DATETIME NOT NULL, 
patientID INT UNSIGNED NOT NULL,
amountCharged FLOAT(9,2), 
amountPaid FLOAT(9,2), 
outstandingBalance FLOAT(9,2), 
serviceType VARCHAR(50)
PRIMARY KEY(billNo),
FOREIGN KEY (dateTime, patientID) REFERENCES Appointment (dateTime, patientID)
FOREIGN KEY (serviceType) REFERENCES Service (type));


DROP TABLE IF EXISTS Claim;
CREATE TABLE IF NOT EXISTS Claim(
billNo INT UNSIGNED NOT NULL, 
amount FLOAT(9,2), 
status_claim VARCHAR(50), 
response VARCHAR(50), 
PRIMARY KEY(billNo),
FOREIGN KEY(billNo) REFERENCES Bill(billNo));